[package]
name = "message-format"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Compile and format message-format catalogs."

[features]
default = ["std"]
std = []
icu4x = [
    "dep:fixed_decimal",
    "dep:icu_locale",
    "dep:icu_plurals",
    "dep:icu_calendar",
    "dep:icu_datetime",
]
compile = [
    "dep:hashbrown",
    "dep:icu_normalizer",
    "dep:libm",
    "dep:serde",
    "dep:toml",
]
profiling = ["dep:profiling"]

[dependencies]
# always-on (runtime)
bitvec = { default-features = false, features = ["alloc"], version = "1.0.1" }
icu_locale_core = { default-features = false, version = "2.1.1" }
profiling = { optional = true, workspace = true }

# icu4x (optional, runtime)
fixed_decimal = { default-features = false, optional = true, version = "0.7.1" }
icu_calendar = { default-features = false, features = [
    "compiled_data",
], optional = true, version = "2.1.1" }
icu_datetime = { default-features = false, features = [
    "compiled_data",
], optional = true, version = "2.1.1" }
icu_locale = { default-features = false, features = [
    "compiled_data",
], optional = true, version = "2.1.1" }
icu_plurals = { default-features = false, features = [
    "compiled_data",
], optional = true, version = "2.1.1" }

# compile (optional)
hashbrown = { default-features = false, features = [
    "default-hasher",
    "raw-entry",
], optional = true, version = "0.17.0" }
icu_normalizer = { default-features = false, features = [
    "compiled_data",
], optional = true, version = "2.1.1" }
libm = { optional = true, version = "0.2" }
serde = { default-features = false, features = [
    "alloc",
    "derive",
], optional = true, version = "1.0" }
toml = { default-features = false, features = [
    "parse",
    "serde",
], optional = true, version = "0.9" }

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true
